![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.4'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [5]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [6]:
array3x3 = [[True,True,True], [True,True,True], [True,True,True]]

array3x3multi = np.array([[True,True,True], [True,True,True], [True,True,True]])
print(array3x3multi)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [8]:
print(my_array[::2])

print(my_array[1::2])

[0 2 4 6 8]
[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [10]:
array_sin_impares = np.array([0,1,2,3,4,5,6,7,8,9])

array_sin_impares[array_sin_impares % 2 != 0] = -1
print(array_sin_impares)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [11]:
array_con_where = np.array([0,1,2,3,4,5,6,7,8,9])

array_con_where = np.where(array_con_where % 2 != 0, -1, array_con_where)

print(array_con_where)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [16]:
print(my_array)

my_array = my_array.reshape((2,5))
print(my_array)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [20]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a, b), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [24]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [25]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

elementos_comunes = np.intersect1d(a, b)
print(elementos_comunes)


[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [28]:
np.concatenate.__doc__

'\n    concatenate(\n        (a1, a2, ...),\n        axis=0,\n        out=None,\n        dtype=None,\n        casting="same_kind"\n    )\n\n    Join a sequence of arrays along an existing axis.\n\n    Parameters\n    ----------\n    a1, a2, ... : sequence of array_like\n        The arrays must have the same shape, except in the dimension\n        corresponding to `axis` (the first, by default).\n    axis : int, optional\n        The axis along which the arrays will be joined.  If axis is None,\n        arrays are flattened before use.  Default is 0.\n    out : ndarray, optional\n        If provided, the destination to place the result. The shape must be\n        correct, matching that of what concatenate would have returned if no\n        out argument were specified.\n    dtype : str or dtype\n        If provided, the destination array will have this dtype. Cannot be\n        provided together with `out`.\n\n        .. versionadded:: 1.20.0\n\n    casting : {\'no\', \'equiv\', \'safe\'

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [30]:
my_array = np.arange(10)
new_array = my_array * 10
print(new_array)
print(my_array[0])
print(my_array[-1])
print(my_array[1:8])


[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [32]:
my_matrix = ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(my_matrix)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

In [ ]:
# No se como hacerlo y no lo encuentro en la teoría....

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [37]:
a = np.array([[1], [2], [3], [4]])
print(a)
a = a.reshape(2, 2)
print(a)


[[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [38]:
jacinto = np.random.rand(4, 5, 3)

print(jacinto)
print(jacinto.shape)


[[[0.81497884 0.24797764 0.25223456]
  [0.70553883 0.65059951 0.47412225]
  [0.76653865 0.46500088 0.83886341]
  [0.7592331  0.45419367 0.66048913]
  [0.2036132  0.6152483  0.70312373]]

 [[0.6241737  0.70858501 0.4028135 ]
  [0.18025045 0.28432329 0.87660999]
  [0.71078007 0.44013091 0.25074058]
  [0.32627921 0.75689976 0.6755778 ]
  [0.96872256 0.8578005  0.37931829]]

 [[0.78228242 0.5386213  0.57558354]
  [0.89979584 0.42996455 0.22531329]
  [0.4066762  0.21953829 0.41768278]
  [0.26534469 0.0863507  0.69931786]
  [0.33094356 0.52443362 0.43242694]]

 [[0.27106097 0.97044531 0.545858  ]
  [0.20599771 0.80960725 0.79134288]
  [0.24655231 0.96088632 0.33008797]
  [0.58905597 0.63512713 0.950738  ]
  [0.97672475 0.7918082  0.79778563]]]
(4, 5, 3)


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [39]:
manolo = np.full((10, 1), False)
print(manolo)
manolo = manolo.reshape(2, 5)
print(manolo)


[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [40]:
x = np.random.randint(10, 20, size=(5, 2, 6))

print(x)
print(x.size)
print(x.ndim)
print(x.shape)


[[[14 12 11 18 13 17]
  [13 13 10 18 19 16]]

 [[12 10 19 13 10 14]
  [16 15 18 12 14 15]]

 [[19 11 18 17 13 13]
  [10 14 17 16 13 19]]

 [[10 13 16 14 11 14]
  [18 13 10 19 17 12]]

 [[14 19 14 12 18 13]
  [16 11 16 18 19 10]]]
60
3
(5, 2, 6)
